### ISSUE TITLE
Possible nonce naming improvement

### ISSUE THREAD

**Issue by wordpressvn** [jeffreyvr/wp-settings#18]
Hello, 
You can change the field data for better optimization, specifically as follows:
resources/views/sections.php
Change
`<?php wp_nonce_field( 'wp_settings_save_' . $settings->option_name, '_wpnonce' ); ?>`
or
`<?php wp_nonce_field( 'wp_settings_save_' . $settings->option_name. '_wpnonce' ); ?>`

**Comment by jeffreyvr** [comment]
Hi! Can you explain me why this would be better than the current code? Is it just the appending of `_wpnonce` to the name? 

https://github.com/jeffreyvr/wp-settings/blob/master/resources/views/sections.php#L8C5-L8C97

Full disclosure, I'm going to edit the name of this issue as I think it gives the impression there is a CSRF vulnerability which, at least for now, I'm not seeing.

**Comment by wordpressvn** [comment]
Because "wp_settings_save" nonce content is not verified

**Comment by jeffreyvr** [comment]
This issue has been stale for a bit. Looking back into it, I truly can't figure out what's wrong with the code as is.

The nonce field [is set](https://github.com/jeffreyvr/wp-settings/blob/master/resources/views/sections.php#L8C5-L8C97), and [is verified](https://github.com/jeffreyvr/wp-settings/blob/master/src/WPSettings.php#L273) - I don't understand what is wrong with the current implementation. If you stil feel I'm overlooking something, please let me know exactly what should be changed.

Thanks for reporting, but for now I'm closing this issue.
