### ISSUE TITLE
New 'css' argument for options

### ISSUE THREAD

**Issue by vikasbhvsr** [jeffreyvr/wp-settings#9]
'css' argument released in 1.1.0 version seems to be required argument. If I don't pass it, I get fatal error. Error is undefined index: label_class. 

I pass following for all options in order for it to work.

Let me know if you need more information.

`
'css' => [
                'input_class' => 'regular-text code',
                'label_class' => 'uat_product_feed_url'
            ],
`

**Comment by jeffreyvr** [comment]
Thanks for testing! Should be fixed now (1.1.0).
